server:
  port: 9090

spring:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: true
    open-in-view: false
  datasource:
    test-while-idle: true
    validation-query: "SELECT 1"
    url: jdbc:postgresql://localhost:5432/lexic
    username: lexic
    password: lexic
